--TUGAS UTAMA 1
--A
SELECT NAMA_PEMBELI FROM PEMBELI WHERE NAMA_PEMBELI LIKE 'C%';
SELECT HARGA_PRODUK FROM PENJUAL WHERE HARGA_PRODUK > 5000;
SELECT JUMLAH_PRODUK FROM PENJUAL WHERE JUMLAH_PRODUK > 10;
--B
SELECT ID_PEMBELI FROM PEMBELI WHERE ID_PEMBELI LIKE '%20';
SELECT ID_PEMBELI FROM PEMBELI WHERE ID_PEMBELI LIKE '13011843%';
--SELECT ID_PENJUAL FROM PENJUAL WHERE ID_PENJUAL LIKE '14%';

--TUGAS UTAMA 2
--A
SELECT NAMA_PEMBELI, ID_PENJUAL FROM TRANSAKSI
JOIN PEMBELI USING(ID_PEMBELI)
WHERE ID_PENJUAL LIKE '14%';

SELECT JUMLAH_PRODUK, ID_PEMBELI FROM TRANSAKSI
JOIN PENJUAL USING(ID_PENJUAL)
WHERE JUMLAH_PRODUK LIKE '2%';

SELECT ALAMAT_PEMBELI, ID_PENJUAL FROM TRANSAKSI
JOIN PEMBELI USING(ID_PEMBELI)
WHERE ALAMAT_PEMBELI LIKE 'A%';

--B
SELECT NAMA_PENJUAL, ID_PEMBELI FROM PENJUAL
NATURAL JOIN PEMBELI
WHERE ID_PEMBELI ='1301184285';

SELECT NAMA_PEMBELI, ID_PENJUAL FROM PEMBELI
NATURAL JOIN PENJUAL
WHERE ID_PENJUAL ='12000000';

--TUGAS UTAMA 3
--A
SELECT NAMA_PEMBELI, NAMA_PRODUK AS "MEMBELI PRODUK", ID_PENJUAL FROM PEMBELI
NATURAL JOIN PENJUAL
NATURAL JOIN TRANSAKSI
WHERE ID_PENJUAL LIKE '%30';

SELECT NAMA_PEMBELI, ALAMAT_PEMBELI AS "ALAMAT PEMBELI", JUMLAH_PRODUK FROM PEMBELI
NATURAL JOIN PENJUAL
NATURAL JOIN TRANSAKSI
WHERE JUMLAH_PRODUK LIKE '2%';

SELECT NAMA_PEMBELI, NAMA_PRODUK AS "MEMBELI PRODUK", JUMLAH_PRODUK FROM PEMBELI
NATURAL JOIN PENJUAL
NATURAL JOIN TRANSAKSI
WHERE JUMLAH_PRODUK > 10;

--B
SELECT NAMA_PEMBELI, NAMA_PRODUK AS "MEMBELI PRODUK", ID_PENJUAL FROM PEMBELI
NATURAL JOIN PENJUAL
NATURAL JOIN TRANSAKSI
WHERE ID_PENJUAL = '10000099';

SELECT NAMA_PEMBELI, NAMA_PRODUK AS "MEMBELI PRODUK", ID_TRANSAKSI FROM PEMBELI
NATURAL JOIN PENJUAL
NATURAL JOIN TRANSAKSI
WHERE ID_TRANSAKSI = '25000001';

CREATE INDEX INDEX_PEMBELI ON PEMBELI(ID_PEMBELI,NAMA_PEMBELI,ALAMAT_PEMBELI,NO_KTP,REKENING_PEMBELI);

CREATE INDEX INDEX_PENJUAL on PENJUAL(ID_PENJUAL,NAMA_PENJUAL, ALAMAT_PENJUAL, REKENING_PENJUAL, NAMA_PRODUK, HARGA_PRODUK, JUMLAH_PRODUK);

CREATE INDEX INDEX_TRANSAKSI on TRANSAKSI(ID_TRANSAKSI, ID_PENJUAL, ID_PEMBELI);
